name: Send dispatch to publisher

on:
  push:
    branches:
      - main

jobs:
  tag-from-backstage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get backstage version
        id: backstage-version
        run: |
          echo "VERSION=v$(jq '.version' backstage.json | sed  s/\"//g)" >> $GITHUB_OUTPUT
      - name: GitHub Actions Create Tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ github.token }}
          tag: ${{ steps.backstage-version.outputs.VERSION }}
