name: Send dispatch to publisher

on:
  push:
    branches:
      - main

jobs:
  tag-from-backstage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get backstage version
        id: backstage-version
        run: |
          echo "VERSION=$(jq '.version' backstage.json | sed  s/\"//g)" >> $GITHUB_OUTPUT

      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.backstage-version.outputs.VERSION }}
