name: Send dispatch to publisher

on:
  push:
    branches:
      - main

jobs:
  push-backstage-version-as-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backstage-bump:
              - 'backstage.json'

      - name: Get backstage version
        if: steps.changes.outputs.backstage-bump == 'true'
        id: backstage-version
        run: |
          echo "VERSION=$(jq '.version' backstage.json | sed  s/\"//g)" >> $GITHUB_OUTPUT

      - name: Push tag
        if: steps.changes.outputs.backstage-bump == 'true'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.backstage-version.outputs.VERSION }}
