name: Send dispatch to publisher

on:
  push:
    branches: 
      - main
      - master
    paths:
      - "**/docs/**"
      - "mkdocs.yaml"
      - "mkdocs.yml"

jobs:
  send-repo-dispatches:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch for service1
        uses: skopecky-test/service1/.github/actions/docs-dispatch@main
        with:
          docs_path: '.'
          entity_name: 'service1'
          entity_kind: 'Component'
          repository: ${{ github.repository }}
          token: ${{ secrets.TOKEN }}
        